BEGIN TRANSACTION;
DROP TABLE IF EXISTS `patient`;
CREATE TABLE IF NOT EXISTS `patient` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`condition`	TEXT,
	`age`	TEXT,
	`notes`	TEXT
);
INSERT INTO `patient` (ID,condition,age,notes) VALUES (1,'healthy','25','none');
DROP TABLE IF EXISTS `Stomping`;
CREATE TABLE IF NOT EXISTS `Stomping` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
DROP TABLE IF EXISTS `Standing`;
CREATE TABLE IF NOT EXISTS `Standing` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
DROP TABLE IF EXISTS `RestingTremors`;
CREATE TABLE IF NOT EXISTS `RestingTremors` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
DROP TABLE IF EXISTS `PracticeSessions`;
CREATE TABLE IF NOT EXISTS `PracticeSessions` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Notes`	TEXT,
	`Data`	BLOB
);
DROP TABLE IF EXISTS `HeelTap`;
CREATE TABLE IF NOT EXISTS `HeelTap` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
DROP TABLE IF EXISTS `HandFlip`;
CREATE TABLE IF NOT EXISTS `HandFlip` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
DROP TABLE IF EXISTS `Grasp`;
CREATE TABLE IF NOT EXISTS `Grasp` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
DROP TABLE IF EXISTS `Gait`;
CREATE TABLE IF NOT EXISTS `Gait` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
DROP TABLE IF EXISTS `FingerTap`;
CREATE TABLE IF NOT EXISTS `FingerTap` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
INSERT INTO `FingerTap` (ID,PatientID,Date,Score,Data) VALUES (1,'',NULL,NULL,NULL);
DROP TABLE IF EXISTS `Devices`;
CREATE TABLE IF NOT EXISTS `Devices` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`DeviceName`	TEXT,
	`Notes`	TEXT
);
DROP TABLE IF EXISTS `Arise`;
CREATE TABLE IF NOT EXISTS `Arise` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	`PatientID`	INTEGER,
	`Date`	TEXT,
	`Score`	INTEGER,
	`Data`	BLOB
);
COMMIT;
