"""users personality

Revision ID: 7cfd2c17be9f
Revises: b5a34b10d18c
Create Date: 2018-05-21 09:53:28.454538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfd2c17be9f'
down_revision = 'b5a34b10d18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('personality', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'personality')
    # ### end Alembic commands ###
