"""users traits

Revision ID: fffbcd5296db
Revises: 7cfd2c17be9f
Create Date: 2018-05-21 09:59:12.079479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffbcd5296db'
down_revision = '7cfd2c17be9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Strategy', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('traits', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'traits')
    op.drop_column('user', 'Strategy')
    # ### end Alembic commands ###
